eid data source: https://www.pxweb.bfs.admin.ch/pxweb/fr/px-x-1703030000_100/-/px-x-1703030000_100.px/table/tableViewLayout2/ $\newline$
2025 population data source: https://www.pxweb.bfs.admin.ch/pxweb/fr/px-x-0102020000_202/-/px-x-0102020000_202.px/
$\newline$
Note: this data analysis was done without any help from AI.

In [368]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import statsmodels.formula.api as smf

In [369]:
cantons_df = pd.read_csv("cantons_data.csv")
eid_df = pd.read_csv("eid_votation.csv")

In [370]:
cantons_df = cantons_df[cantons_df["Sex"] != "Sexe - total"]
cantons_df = cantons_df[cantons_df["Age"] != "100 ans ou plus"]
cantons_df = cantons_df[cantons_df["Canton"] != "Suisse"]
cantons_df = cantons_df[cantons_df["Canton"] != "Sans indication"]
col = ["Canton", "Age", "Sex", "Count", "Immigration", "Swiss citizenship acquisition"]
cantons_df = cantons_df[col]

cantons_df.head()

     Canton     Age    Sex  Count  Immigration  Swiss citizenship acquisition
332  Z�rich  18 ans  Homme   6227           29                            106
333  Z�rich  19 ans  Homme   5993           34                             74
334  Z�rich  20 ans  Homme   6065           39                             63
335  Z�rich  21 ans  Homme   5925           32                             42
336  Z�rich  22 ans  Homme   5819           38                             28

In [371]:
cantons_df["Canton"].unique()

array(['Z�rich', 'Bern / Berne', 'Luzern', 'Uri', 'Schwyz', 'Obwalden',
       'Nidwalden', 'Glarus', 'Zug', 'Fribourg / Freiburg', 'Solothurn',
       'Basel-Stadt', 'Basel-Landschaft', 'Schaffhausen',
       'Appenzell Ausserrhoden', 'Appenzell Innerrhoden', 'St. Gallen',
       'Graub�nden / Grigioni / Grischun', 'Aargau', 'Thurgau', 'Ticino',
       'Vaud', 'Valais / Wallis', 'Neuch�tel', 'Gen�ve', 'Jura'],
      dtype=object)

In [372]:
def fix_cantons(cantons_df):
    cantons_df = cantons_df.replace('Z�rich','Zurich')
    cantons_df = cantons_df.replace('Bern / Berne','Berne')
    cantons_df = cantons_df.replace('Fribourg / Freiburg','Fribourg')
    cantons_df = cantons_df.replace('Graub�nden / Grigioni / Grischun','Grischun')
    cantons_df = cantons_df.replace('Valais / Wallis','Valais')
    cantons_df = cantons_df.replace('Neuch�tel','Neuchatel')
    cantons_df = cantons_df.replace('Gen�ve','Geneve')

    return cantons_df

cantons_df = fix_cantons(cantons_df)
eid_df = fix_cantons(eid_df)

In [373]:
cantons_df["Canton"].unique()

array(['Zurich', 'Berne', 'Luzern', 'Uri', 'Schwyz', 'Obwalden',
       'Nidwalden', 'Glarus', 'Zug', 'Fribourg', 'Solothurn',
       'Basel-Stadt', 'Basel-Landschaft', 'Schaffhausen',
       'Appenzell Ausserrhoden', 'Appenzell Innerrhoden', 'St. Gallen',
       'Grischun', 'Aargau', 'Thurgau', 'Ticino', 'Vaud', 'Valais',
       'Neuchatel', 'Geneve', 'Jura'], dtype=object)

In [374]:
eid_df.head()

,Canton,Voter registrations,Vote count,Participation %,Valid votes,Yes,No,yes_percentage
0,Suisse,5641040,2796897,49.58,2747948,1384586,1363362,50.39
1,Zurich,976490,509297,52.16,503923,274702,229221,54.51
2,Berne,750745,358855,47.80,354158,171771,182387,48.50
3,Luzern,288363,153604,53.27,151603,80261,71342,52.94
4,Uri,27226,12731,46.76,12567,5109,7458,40.65

In [375]:
cantons_df.head()

     Canton     Age    Sex  Count  Immigration  Swiss citizenship acquisition
332  Zurich  18 ans  Homme   6227           29                            106
333  Zurich  19 ans  Homme   5993           34                             74
334  Zurich  20 ans  Homme   6065           39                             63
335  Zurich  21 ans  Homme   5925           32                             42
336  Zurich  22 ans  Homme   5819           38                             28

In [376]:
# for later graphs that have to do with age groups

age_groups = [range(18, 24), range(24,30), range(30, 36), range(36, 42), range(42, 48), range(48, 54), range(54, 60), range(60, 66),
              range(66, 72), range(72, 78), range(78, 84), range(84, 90), range(90, 96)]
def age_sort(df, age_groups):
    for i in range(95, 100):
        df = df[df["Age"] != str(i) + " ans"]
    # group by ages to count population groups
    for age_group in age_groups:
        new_string = str(age_group[0]) + " - " + str(age_group[-1])
        for age in age_group:
            age_string = str(age) + " ans"
            df = df.replace(age_string, new_string)
    df.reset_index()
    return df

In [377]:
def age_transform(df):
    for i in range(18, 100):
        age_string = str(i) + " ans"
        df = df.replace(age_string, i)
    return df

In [378]:
# represent demographics with percentages instead of count
def canton_proportions(df):
    df["Count"] = df["Count"] / df.groupby("Canton")["Count"].transform('sum')
    return df

In [379]:
cantons_df = canton_proportions(cantons_df)
cantons_df = cantons_df.rename(columns={"Count":"Proportion"})
cantons_df = cantons_df.replace("Homme","Male")
cantons_df = cantons_df.replace("Femme","Female")
cantons_df.head()

,Canton,Age,Sex,Proportion,Immigration,Swiss citizenship acquisition
332,Zurich,18 ans,Male,0.006559,29,106
333,Zurich,19 ans,Male,0.006313,34,74
334,Zurich,20 ans,Male,0.006389,39,63
335,Zurich,21 ans,Male,0.006241,32,42
336,Zurich,22 ans,Male,0.006129,38,28

In [380]:
#cantons_df = age_sort(cantons_df, age_groups)
cantons_df = age_transform(cantons_df)
cantons_df = cantons_df.groupby(["Canton", "Age", "Sex"]).sum()
cantons_df.head(10)

/var/folders/22/_dymvqsd4tgfb0zzj_kpnj340000gn/T/ipykernel_2023/749895442.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace(age_string, i)

                   Proportion  Immigration  Swiss citizenship acquisition
Canton Age Sex
Aargau 18  Female    0.005881            4                             27
           Male      0.006156           11                             33
       19  Female    0.005886            9                             26
           Male      0.006318           11                             30
       20  Female    0.005799           10                             19
           Male      0.006334            2                             18
       21  Female    0.005981            8                             16
           Male      0.006297           12                             18
       22  Female    0.005831           10                             22
           Male      0.006274            7                             15

In [381]:
cantons_df = cantons_df.reset_index()
cantons_df.pivot(columns=["Age", "Sex"], index="Canton", values=["Proportion"])

                       Proportion                                          \
Age                            18                  19                  20
Sex                        Female      Male    Female      Male    Female
Canton
Aargau                   0.005881  0.006156  0.005886  0.006318  0.005799
Appenzell Ausserrhoden   0.005432  0.006064  0.005827  0.006381  0.005405
Appenzell Innerrhoden    0.006594  0.006343  0.005175  0.006594  0.005509
Basel-Landschaft         0.005809  0.005951  0.005666  0.005534  0.005698
Basel-Stadt              0.005025  0.005493  0.005121  0.005454  0.005331
Berne                    0.005613  0.005788  0.005465  0.005871  0.005518
Fribourg                 0.006465  0.006671  0.006451  0.006859  0.006263
Geneve                   0.007414  0.007885  0.007327  0.007719  0.007933
Glarus                   0.004989  0.006255  0.005296  0.005948  0.005027
Grischun                 0.005218  0.005096  0.005125  0.005182  0.004937
Jura                     0.005981  0.005866  0.006020  0.007285  0.006633
Luzern                   0.006092  0.006218  0.006152  0.006085  0.005775
Neuchatel                0.006606  0.006670  0.007120  0.007422  0.007028
Nidwalden                0.005045  0.005360  0.005392  0.005770  0.005329
Obwalden                 0.006249  0.007016  0.005627  0.006249  0.006176
Schaffhausen             0.005467  0.005882  0.005071  0.005486  0.005674
Schwyz                   0.005402  0.005820  0.005662  0.005774  0.005616
Solothurn                0.005433  0.005229  0.005025  0.005417  0.005251
St. Gallen               0.006020  0.006214  0.005842  0.006417  0.006024
Thurgau                  0.006320  0.006287  0.005726  0.006203  0.005738
Ticino                   0.005890  0.006353  0.005913  0.006533  0.006089
Uri                      0.005848  0.006107  0.005811  0.006662  0.005441
Valais                   0.005462  0.005872  0.005716  0.006113  0.005777
Vaud                     0.007085  0.007535  0.007096  0.007645  0.007078
Zug                      0.005962  0.005898  0.006411  0.006411  0.005770
Zurich                   0.006100  0.006559  0.006137  0.006313  0.006096

                                                                          ...  \
Age                                     21                  22            ...
Sex                         Male    Female      Male    Female      Male  ...
Canton                                                                    ...
Aargau                  0.006334  0.005981  0.006297  0.005831  0.006274  ...
Appenzell Ausserrhoden  0.006275  0.005194  0.004772  0.005511  0.005273  ...
Appenzell Innerrhoden   0.005843  0.006010  0.005425  0.005843  0.005759  ...
Basel-Landschaft        0.006020  0.005708  0.005703  0.005291  0.005698  ...
Basel-Stadt             0.005702  0.005521  0.005540  0.005454  0.005617  ...
Berne                   0.005702  0.005612  0.005725  0.005496  0.005580  ...
Fribourg                0.006732  0.006676  0.006920  0.006742  0.006723  ...
Geneve                  0.007889  0.008126  0.007960  0.007486  0.007351  ...
Glarus                  0.005680  0.005526  0.005066  0.004912  0.006179  ...
Grischun                0.005276  0.005261  0.005477  0.005348  0.005880  ...
Jura                    0.006882  0.006346  0.006748  0.006595  0.006710  ...
Luzern                  0.006232  0.005969  0.006123  0.005694  0.005941  ...
Neuchatel               0.007422  0.006881  0.007468  0.006918  0.007065  ...
Nidwalden               0.005581  0.004824  0.005486  0.005013  0.005959  ...
Obwalden                0.005189  0.006212  0.005920  0.005591  0.005701  ...
Schaffhausen            0.005486  0.005090  0.005411  0.005542  0.005693  ...
Schwyz                  0.006081  0.005430  0.006090  0.005467  0.005858  ...
Solothurn               0.005935  0.005472  0.005819  0.005461  0.005985  ...
St. Gallen              0.006340  0.006251  0.006650  0.006500  0.006411  ...
Thurgau                 0.006091  0.006012  0.006275  0.005810  0.005866  ...
Ticino                  0.006482  0.006163  0.006181  0.005927  0.006121  ...
Uri                     0.006255  0.006662  0.006366  0.005626  0.006255  ...
Valais                  0.006229  0.005574  0.005859  0.005600  0.006044  ...
Vaud                    0.007450  0.007204  0.007422  0.006981  0.007264  ...
Zug                     0.005731  0.005552  0.006539  0.005975  0.006436  ...
Zurich                  0.006389  0.006083  0.006241  0.005880  0.006129  ...

                                                                          \
Age                           95                  96                  97
Sex                       Female      Male    Female      Male    Female
Canton
Aargau                  0.000857  0.000418  0.000655  0.000266  0.000466
Appenzell Ausserrhoden  0.000844  0.000316  0.000870  0.000264  0.000633
Appenzell Innerrhoden   0.000918  0.000250  0.000501  0.000334  0.000334
Basel-Landschaft        0.001247  0.000560  0.000978  0.000391  0.000698
Basel-Stadt             0.001859  0.000954  0.001526  0.000505  0.001287
Berne                   0.001105  0.000414  0.000841  0.000323  0.000630
Fribourg                0.000738  0.000268  0.000573  0.000146  0.000343
Geneve                  0.001476  0.000538  0.001044  0.000356  0.000732
Glarus                  0.001382  0.000537  0.000921  0.000345  0.000652
Grischun                0.001000  0.000396  0.000749  0.000266  0.000590
Jura                    0.001246  0.000403  0.000748  0.000211  0.000748
Luzern                  0.000950  0.000390  0.000696  0.000278  0.000538
Neuchatel               0.001239  0.000376  0.001018  0.000349  0.000844
Nidwalden               0.000883  0.000378  0.000473  0.000378  0.000378
Obwalden                0.001096  0.000365  0.000877  0.000256  0.000512
Schaffhausen            0.001433  0.000584  0.000943  0.000283  0.000754
Schwyz                  0.000781  0.000353  0.000576  0.000279  0.000539
Solothurn               0.001015  0.000458  0.000849  0.000364  0.000618
St. Gallen              0.000922  0.000396  0.000620  0.000261  0.000479
Thurgau                 0.000784  0.000415  0.000572  0.000269  0.000403
Ticino                  0.001564  0.000555  0.001087  0.000361  0.000800
Uri                     0.001036  0.000518  0.000555  0.000333  0.000370
Valais                  0.000944  0.000418  0.000767  0.000246  0.000543
Vaud                    0.001254  0.000484  0.000837  0.000346  0.000757
Zug                     0.000872  0.000410  0.000680  0.000346  0.000500
Zurich                  0.000991  0.000457  0.000767  0.000321  0.000573


Age                                     98                  99
Sex                         Male    Female      Male    Female      Male
Canton
Aargau                  0.000193  0.000334  0.000130  0.000241  0.000052
Appenzell Ausserrhoden  0.000264  0.000554  0.000079  0.000211  0.000026
Appenzell Innerrhoden   0.000083  0.000250  0.000167  0.000083  0.000083
Basel-Landschaft        0.000333  0.000523  0.000143  0.000317  0.000122
Basel-Stadt             0.000353  0.000849  0.000191  0.000477  0.000143
Berne                   0.000228  0.000495  0.000113  0.000320  0.000080
Fribourg                0.000146  0.000315  0.000080  0.000211  0.000070
Geneve                  0.000285  0.000681  0.000186  0.000400  0.000107
Glarus                  0.000115  0.000384  0.000192  0.000307  0.000000
Grischun                0.000187  0.000410  0.000151  0.000209  0.000122
Jura                    0.000326  0.000652  0.000211  0.000460  0.000115
Luzern                  0.000155  0.000383  0.000120  0.000218  0.000067
Neuchatel               0.000266  0.000706  0.000119  0.000422  0.000083
Nidwalden               0.000252  0.000189  0.000158  0.000284  0.000095
Obwalden                0.000146  0.000292  0.000000  0.000146  0.000110
Schaffhausen            0.000434  0.000566  0.000113  0.000358  0.000189
Schwyz                  0.000214  0.000325  0.000112  0.000260  0.000065
Solothurn               0.000210  0.000359  0.000116  0.000281  0.000072
St. Gallen              0.000166  0.000393  0.000098  0.000304  0.000040
Thurgau                 0.000263  0.000398  0.000095  0.000286  0.000062
Ticino                  0.000208  0.000685  0.000176  0.000541  0.000102
Uri                     0.000148  0.000333  0.000111  0.000333  0.000148
Valais                  0.000194  0.000349  0.000121  0.000285  0.000078
Vaud                    0.000195  0.000458  0.000121  0.000344  0.000074
Zug                     0.000333  0.000321  0.000115  0.000256  0.000077
Zurich                  0.000181  0.000400  0.000134  0.000253  0.000078

[26 rows x 164 columns]

In [382]:
eid_df = eid_df.groupby(["Canton"]).sum()
eid_df.head(10)

,Voter registrations,Vote count,Participation %,Valid votes,Yes,No,yes_percentage
Canton,,,,,,,
Aargau,447798,232292,51.87,230470,113121,117349,49.08
Appenzell Ausserrhoden,39526,21896,55.40,21652,9949,11703,45.95
Appenzell Innerrhoden,12385,6006,48.49,5859,2644,3215,45.13
Basel-Landschaft,192244,96303,50.09,93940,46245,47695,49.23
Basel-Stadt,114378,55409,48.44,54544,30976,23568,56.79
Berne,750745,358855,47.80,354158,171771,182387,48.50
Fribourg,219163,100846,46.01,98853,49792,49061,50.37
Geneve,285837,119086,41.66,112906,62308,50598,55.19
Glarus,26836,12159,45.31,12008,4965,7043,41.35
Grischun,142771,67835,47.51,66445,32065,34380,48.26

In [383]:
data_df = pd.merge(left=eid_df, right=cantons_df, left_on="Canton", right_on="Canton", how="inner")
data_df

,Canton,Voter registrations,Vote count,Participation %,Valid votes,Yes,No,yes_percentage,Age,Sex,Proportion,Immigration,Swiss citizenship acquisition
0,Aargau,447798,232292,51.87,230470,113121,117349,49.08,18,Female,0.005881,4,27
1,Aargau,447798,232292,51.87,230470,113121,117349,49.08,18,Male,0.006156,11,33
2,Aargau,447798,232292,51.87,230470,113121,117349,49.08,19,Female,0.005886,9,26
3,Aargau,447798,232292,51.87,230470,113121,117349,49.08,19,Male,0.006318,11,30
4,Aargau,447798,232292,51.87,230470,113121,117349,49.08,20,Female,0.005799,10,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4259,Zurich,976490,509297,52.16,503923,274702,229221,54.51,97,Male,0.000181,0,0
4260,Zurich,976490,509297,52.16,503923,274702,229221,54.51,98,Female,0.000400,0,0
4261,Zurich,976490,509297,52.16,503923,274702,229221,54.51,98,Male,0.000134,0,0
4262,Zurich,976490,509297,52.16,503923,274702,229221,54.51,99,Female,0.000253,0,0
4263,Zurich,976490,509297,52.16,503923,274702,229221,54.51,99,Male,0.000078,0,0

In [386]:
model = smf.ols(formula='yes_percentage ~ Age*C(Sex) + Immigration', data=data_df).fit()

In [387]:
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:         yes_percentage   R-squared:                       0.225
Model:                            OLS   Adj. R-squared:                  0.224
Method:                 Least Squares   F-statistic:                     308.6
Date:                Mon, 27 Apr 2026   Prob (F-statistic):          2.14e-233
Time:                        17:25:25   Log-Likelihood:                -12172.
No. Observations:                4264   AIC:                         2.435e+04
Df Residuals:                    4259   BIC:                         2.439e+04
Df Model:                           4
Covariance Type:            nonrobust
======================================================================================
                         coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------
Intercept             44.3248      0.264    168.079      0.000      43.808      44.842
C(Sex)[T.Male]        -0.4074      0.344     -1.186      0.236      -1.081       0.266
Age                    0.0395      0.004      9.843      0.000       0.032       0.047
Age:C(Sex)[T.Male]     0.0039      0.005      0.721      0.471      -0.007       0.015
Immigration            0.3147      0.009     35.131      0.000       0.297       0.332
==============================================================================
Omnibus:                      190.634   Durbin-Watson:                   0.073
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              158.666
Skew:                           0.397   Prob(JB):                     3.52e-35
Kurtosis:                       2.489   Cond. No.                         444.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.