eid data source: https://www.pxweb.bfs.admin.ch/pxweb/fr/px-x-1703030000_100/-/px-x-1703030000_100.px/table/tableViewLayout2/ $\newline$
2025 population data source: https://www.pxweb.bfs.admin.ch/pxweb/fr/px-x-0102020000_202/-/px-x-0102020000_202.px/
$\newline$
Note: this data analysis was done without any help from AI.

In [ ]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import statsmodels.api as smf

In [311]:
cantons_df = pd.read_csv("cantons_data.csv")
eid_df = pd.read_csv("eid_votation.csv")

In [312]:
cantons_df = cantons_df[cantons_df["Sex"] != "Sexe - total"]
cantons_df = cantons_df[cantons_df["Age"] != "100 ans ou plus"]
cantons_df = cantons_df[cantons_df["Canton"] != "Suisse"]
cantons_df = cantons_df[cantons_df["Canton"] != "Sans indication"]
col = ["Canton", "Age", "Sex", "Count", "Immigration", "Swiss citizenship acquisition"]
cantons_df = cantons_df[col]

cantons_df.head()

     Canton     Age    Sex  Count  Immigration  Swiss citizenship acquisition
332  Z�rich  18 ans  Homme   6227           29                            106
333  Z�rich  19 ans  Homme   5993           34                             74
334  Z�rich  20 ans  Homme   6065           39                             63
335  Z�rich  21 ans  Homme   5925           32                             42
336  Z�rich  22 ans  Homme   5819           38                             28

In [313]:
cantons_df["Canton"].unique()

array(['Z�rich', 'Bern / Berne', 'Luzern', 'Uri', 'Schwyz', 'Obwalden',
       'Nidwalden', 'Glarus', 'Zug', 'Fribourg / Freiburg', 'Solothurn',
       'Basel-Stadt', 'Basel-Landschaft', 'Schaffhausen',
       'Appenzell Ausserrhoden', 'Appenzell Innerrhoden', 'St. Gallen',
       'Graub�nden / Grigioni / Grischun', 'Aargau', 'Thurgau', 'Ticino',
       'Vaud', 'Valais / Wallis', 'Neuch�tel', 'Gen�ve', 'Jura'],
      dtype=object)

In [314]:
def fix_cantons(cantons_df):
    cantons_df = cantons_df.replace('Z�rich','Zurich')
    cantons_df = cantons_df.replace('Bern / Berne','Berne')
    cantons_df = cantons_df.replace('Fribourg / Freiburg','Fribourg')
    cantons_df = cantons_df.replace('Graub�nden / Grigioni / Grischun','Grischun')
    cantons_df = cantons_df.replace('Valais / Wallis','Valais')
    cantons_df = cantons_df.replace('Neuch�tel','Neuchatel')
    cantons_df = cantons_df.replace('Gen�ve','Geneve')

    return cantons_df

cantons_df = fix_cantons(cantons_df)
eid_df = fix_cantons(eid_df)

In [315]:
cantons_df["Canton"].unique()

array(['Zurich', 'Berne', 'Luzern', 'Uri', 'Schwyz', 'Obwalden',
       'Nidwalden', 'Glarus', 'Zug', 'Fribourg', 'Solothurn',
       'Basel-Stadt', 'Basel-Landschaft', 'Schaffhausen',
       'Appenzell Ausserrhoden', 'Appenzell Innerrhoden', 'St. Gallen',
       'Grischun', 'Aargau', 'Thurgau', 'Ticino', 'Vaud', 'Valais',
       'Neuchatel', 'Geneve', 'Jura'], dtype=object)

In [316]:
eid_df.head()

,Canton,Voter registrations,Vote count,Participation %,Valid votes,Yes,No,Yes %
0,Suisse,5641040,2796897,49.58,2747948,1384586,1363362,50.39
1,Zurich,976490,509297,52.16,503923,274702,229221,54.51
2,Berne,750745,358855,47.80,354158,171771,182387,48.50
3,Luzern,288363,153604,53.27,151603,80261,71342,52.94
4,Uri,27226,12731,46.76,12567,5109,7458,40.65

In [ ]:
cantons_df.head()

     Canton     Age    Sex  Count  Immigration  Swiss citizenship acquisition
332  Zurich  18 ans  Homme   6227           29                            106
333  Zurich  19 ans  Homme   5993           34                             74
334  Zurich  20 ans  Homme   6065           39                             63
335  Zurich  21 ans  Homme   5925           32                             42
336  Zurich  22 ans  Homme   5819           38                             28

In [ ]:
# for later graphs that have to do with age groups

age_groups = [range(18, 24), range(24,30), range(30, 36), range(36, 42), range(42, 48), range(48, 54), range(54, 60), range(60, 66),
              range(66, 72), range(72, 78), range(78, 84), range(84, 90), range(90, 96)]
def age_sort(df, age_groups):
    for i in range(95, 100):
        df = df[df["Age"] != str(i) + " ans"]
    # group by ages to count population groups
    for age_group in age_groups:
        new_string = str(age_group[0]) + " - " + str(age_group[-1])
        for age in age_group:
            age_string = str(age) + " ans"
            df = df.replace(age_string, new_string)
    df.reset_index()
    return df

In [ ]:
def age_transform(df):
    for i in range(18, 100):
        age_string = str(i) + " ans"
        df = df.replace(age_string, i)
    return df

In [319]:
# represent demographics with percentages instead of count
def canton_proportions(df):
    df["Count"] = df["Count"] / df.groupby("Canton")["Count"].transform('sum')
    return df

In [320]:
cantons_df = canton_proportions(cantons_df)
cantons_df = cantons_df.rename(columns={"Count":"Proportion"})
cantons_df = cantons_df.replace("Homme","Male")
cantons_df = cantons_df.replace("Femme","Female")
cantons_df.head()

,Canton,Age,Sex,Proportion,Immigration,Swiss citizenship acquisition
332,Zurich,18 ans,Male,0.006559,29,106
333,Zurich,19 ans,Male,0.006313,34,74
334,Zurich,20 ans,Male,0.006389,39,63
335,Zurich,21 ans,Male,0.006241,32,42
336,Zurich,22 ans,Male,0.006129,38,28

In [ ]:
cantons_df = age_sort(cantons_df, age_groups)
cantons_df = cantons_df.groupby(["Canton", "Age", "Sex"]).sum()
cantons_df.head(10)

                       Proportion  Immigration  Swiss citizenship acquisition
Canton Age     Sex
Aargau 18 - 23 Female    0.035195           53                            130
               Male      0.037526           52                            123
       24 - 29 Female    0.037362           76                             89
               Male      0.039086           71                             37
       30 - 35 Female    0.042295           57                            123
               Male      0.041897           79                             88
       36 - 41 Female    0.044499           50                            224
               Male      0.044360           57                            213
       42 - 47 Female    0.045031           35                            228
               Male      0.044403           50                            208

In [322]:
cantons_df = cantons_df.reset_index()
cantons_df.pivot(columns=["Age", "Sex"], index="Canton", values=["Proportion"])

                       Proportion                                          \
Age                       18 - 23             24 - 29             30 - 35
Sex                        Female      Male    Female      Male    Female
Canton
Aargau                   0.035195  0.037526  0.037362  0.039086  0.042295
Appenzell Ausserrhoden   0.032458  0.034014  0.033302  0.036835  0.038470
Appenzell Innerrhoden    0.036391  0.036558  0.040230  0.044821  0.042985
Basel-Landschaft         0.033515  0.034915  0.034461  0.036438  0.036480
Basel-Stadt              0.032536  0.033356  0.041357  0.040565  0.048737
Berne                    0.033202  0.034375  0.036659  0.036731  0.042369
Fribourg                 0.039032  0.040677  0.043477  0.044365  0.046958
Geneve                   0.045883  0.046939  0.046998  0.047323  0.044977
Glarus                   0.030969  0.034462  0.035114  0.037071  0.038414
Grischun                 0.031511  0.032252  0.035037  0.037794  0.037218
Jura                     0.038035  0.040796  0.038726  0.043825  0.039032
Luzern                   0.035619  0.036902  0.042016  0.042681  0.046135
Neuchatel                0.041589  0.043874  0.040818  0.043791  0.041075
Nidwalden                0.030143  0.034463  0.030427  0.035819  0.038405
Obwalden                 0.035665  0.035774  0.033838  0.037748  0.038625
Schaffhausen             0.032802  0.033632  0.034989  0.039363  0.036460
Schwyz                   0.033277  0.035397  0.036002  0.038168  0.039432
Solothurn                0.032488  0.034066  0.036349  0.037270  0.040503
St. Gallen               0.037094  0.038589  0.041237  0.042976  0.043283
Thurgau                  0.035569  0.036818  0.036123  0.039138  0.042074
Ticino                   0.036371  0.038453  0.036778  0.038287  0.034317
Uri                      0.035940  0.038198  0.036199  0.041974  0.039309
Valais                   0.033850  0.036458  0.038971  0.039959  0.041269
Vaud                     0.042447  0.044596  0.044358  0.043928  0.045681
Zug                      0.035169  0.036657  0.036054  0.036336  0.040118
Zurich                   0.036394  0.037786  0.039810  0.039636  0.046078

                                                                          ...  \
Age                                36 - 41             42 - 47            ...
Sex                         Male    Female      Male    Female      Male  ...
Canton                                                                    ...
Aargau                  0.041897  0.044499  0.044360  0.045031  0.044403  ...
Appenzell Ausserrhoden  0.041792  0.045088  0.044376  0.043585  0.044481  ...
Appenzell Innerrhoden   0.048911  0.042567  0.044070  0.038227  0.043235  ...
Basel-Landschaft        0.034915  0.039313  0.037896  0.040655  0.038018  ...
Basel-Stadt             0.048318  0.045047  0.044332  0.041700  0.040909  ...
Berne                   0.041805  0.044037  0.043042  0.043897  0.042223  ...
Fribourg                0.046779  0.044299  0.043679  0.043486  0.042203  ...
Geneve                  0.044640  0.041993  0.038907  0.043928  0.039695  ...
Glarus                  0.040870  0.042866  0.045667  0.042022  0.043480  ...
Grischun                0.038327  0.039709  0.040212  0.039615  0.039442  ...
Jura                    0.042521  0.039262  0.040374  0.039109  0.037997  ...
Luzern                  0.046466  0.045470  0.045681  0.045147  0.043297  ...
Neuchatel               0.042112  0.040580  0.037818  0.041029  0.037626  ...
Nidwalden               0.040864  0.040202  0.043985  0.039414  0.039571  ...
Obwalden                0.039721  0.043813  0.045567  0.044764  0.041475  ...
Schaffhausen            0.038458  0.040739  0.041455  0.040701  0.041154  ...
Schwyz                  0.042789  0.042278  0.043607  0.042529  0.044518  ...
Solothurn               0.040497  0.043305  0.043051  0.041617  0.040971  ...
St. Gallen              0.045516  0.043550  0.044843  0.041944  0.041916  ...
Thurgau                 0.042281  0.044422  0.045402  0.042091  0.042326  ...
Ticino                  0.035506  0.033692  0.033378  0.038981  0.035788  ...
Uri                     0.041863  0.040974  0.041900  0.038087  0.039049  ...
Valais                  0.042821  0.040898  0.040519  0.039989  0.039079  ...
Vaud                    0.044322  0.044168  0.041589  0.045524  0.041794  ...
Zug                     0.041388  0.040670  0.043914  0.043183  0.043606  ...
Zurich                  0.046142  0.046991  0.046680  0.049019  0.047799  ...

                                                                          \
Age                      66 - 71             72 - 77             78 - 83
Sex                       Female      Male    Female      Male    Female
Canton
Aargau                  0.048370  0.044881  0.040098  0.036389  0.033046
Appenzell Ausserrhoden  0.049913  0.049781  0.042820  0.040869  0.032168
Appenzell Innerrhoden   0.043819  0.049412  0.037226  0.038227  0.028044
Basel-Landschaft        0.050396  0.045650  0.046638  0.038916  0.042463
Basel-Stadt             0.047679  0.040899  0.042987  0.034520  0.039564
Berne                   0.049136  0.044601  0.044027  0.038606  0.038440
Fribourg                0.044003  0.042006  0.037299  0.034057  0.031191
Geneve                  0.042520  0.035264  0.038290  0.027454  0.036965
Glarus                  0.052690  0.052537  0.043825  0.043135  0.036150
Grischun                0.053355  0.050685  0.046028  0.043905  0.038284
Jura                    0.051570  0.045704  0.043652  0.039933  0.036099
Luzern                  0.044901  0.042706  0.037275  0.034054  0.031064
Neuchatel               0.046929  0.040433  0.043075  0.033424  0.038809
Nidwalden               0.050166  0.053823  0.042157  0.043323  0.035346
Obwalden                0.047906  0.048564  0.040634  0.040598  0.030330
Schaffhausen            0.053030  0.048808  0.046263  0.038741  0.039287
Schwyz                  0.046322  0.048684  0.039237  0.037787  0.030116
Solothurn               0.051192  0.048909  0.042383  0.039289  0.034490
St. Gallen              0.047706  0.044072  0.040131  0.036154  0.034796
Thurgau                 0.050563  0.048125  0.040555  0.038157  0.032700
Ticino                  0.048822  0.042682  0.045333  0.036556  0.041373
Uri                     0.048858  0.050672  0.040937  0.042566  0.035015
Valais                  0.050077  0.046464  0.044653  0.038825  0.037312
Vaud                    0.042942  0.036891  0.039206  0.030329  0.035626
Zug                     0.044709  0.043221  0.038490  0.034772  0.033990
Zurich                  0.041987  0.037511  0.037518  0.030947  0.033233


Age                                84 - 89             90 - 95
Sex                         Male    Female      Male    Female      Male
Canton
Aargau                  0.028457  0.019362  0.013934  0.008244  0.004605
Appenzell Ausserrhoden  0.029320  0.022017  0.013711  0.009334  0.005142
Appenzell Innerrhoden   0.029046  0.021367  0.016526  0.009432  0.005676
Basel-Landschaft        0.034197  0.027807  0.019228  0.012082  0.007220
Basel-Stadt             0.027711  0.030038  0.016459  0.016058  0.006990
Berne                   0.031406  0.023420  0.015478  0.010339  0.005182
Fribourg                0.025910  0.017463  0.012450  0.007343  0.003547
Geneve                  0.024573  0.023038  0.013772  0.010896  0.005313
Glarus                  0.029665  0.022143  0.016041  0.010553  0.004643
Grischun                0.032151  0.023464  0.016641  0.009925  0.005197
Jura                    0.028852  0.021625  0.014052  0.010966  0.005272
Luzern                  0.025602  0.020776  0.014027  0.009296  0.004741
Neuchatel               0.029332  0.023175  0.013955  0.011790  0.005037
Nidwalden               0.033328  0.020747  0.015135  0.007567  0.005423
Obwalden                0.029306  0.019221  0.015457  0.008258  0.005006
Schaffhausen            0.032067  0.027430  0.017476  0.010991  0.006202
Schwyz                  0.027717  0.019191  0.013714  0.008452  0.004770
Solothurn               0.030100  0.022091  0.015191  0.010232  0.005212
St. Gallen              0.029086  0.021674  0.014489  0.009184  0.004798
Thurgau                 0.027999  0.019661  0.013089  0.008696  0.004449
Ticino                  0.031036  0.027474  0.017938  0.013172  0.006329
Uri                     0.031129  0.020802  0.015435  0.009179  0.004997
Valais                  0.030173  0.021391  0.014494  0.009437  0.005117
Vaud                    0.026474  0.020727  0.012732  0.009835  0.004774
Zug                     0.029528  0.021245  0.015104  0.008847  0.004744
Zurich                  0.026730  0.021014  0.013972  0.009352  0.005090

[26 rows x 26 columns]

In [324]:
eid_df = eid_df.groupby(["Canton"]).sum()
eid_df.head(10)

,Voter registrations,Vote count,Participation %,Valid votes,Yes,No,Yes %
Canton,,,,,,,
Aargau,447798,232292,51.87,230470,113121,117349,49.08
Appenzell Ausserrhoden,39526,21896,55.40,21652,9949,11703,45.95
Appenzell Innerrhoden,12385,6006,48.49,5859,2644,3215,45.13
Basel-Landschaft,192244,96303,50.09,93940,46245,47695,49.23
Basel-Stadt,114378,55409,48.44,54544,30976,23568,56.79
Berne,750745,358855,47.80,354158,171771,182387,48.50
Fribourg,219163,100846,46.01,98853,49792,49061,50.37
Geneve,285837,119086,41.66,112906,62308,50598,55.19
Glarus,26836,12159,45.31,12008,4965,7043,41.35
Grischun,142771,67835,47.51,66445,32065,34380,48.26

In [327]:
data_df = pd.merge(left=eid_df, right=cantons_df, left_on="Canton", right_on="Canton", how="inner")
data_df

,Canton,Voter registrations,Vote count,Participation %,Valid votes,Yes,No,Yes %,Age,Sex,Proportion,Immigration,Swiss citizenship acquisition
0,Aargau,447798,232292,51.87,230470,113121,117349,49.08,18 - 23,Female,0.035195,53,130
1,Aargau,447798,232292,51.87,230470,113121,117349,49.08,18 - 23,Male,0.037526,52,123
2,Aargau,447798,232292,51.87,230470,113121,117349,49.08,24 - 29,Female,0.037362,76,89
3,Aargau,447798,232292,51.87,230470,113121,117349,49.08,24 - 29,Male,0.039086,71,37
4,Aargau,447798,232292,51.87,230470,113121,117349,49.08,30 - 35,Female,0.042295,57,123
...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,Zurich,976490,509297,52.16,503923,274702,229221,54.51,78 - 83,Male,0.026730,34,4
672,Zurich,976490,509297,52.16,503923,274702,229221,54.51,84 - 89,Female,0.021014,18,2
673,Zurich,976490,509297,52.16,503923,274702,229221,54.51,84 - 89,Male,0.013972,14,0
674,Zurich,976490,509297,52.16,503923,274702,229221,54.51,90 - 95,Female,0.009352,2,0
675,Zurich,976490,509297,52.16,503923,274702,229221,54.51,90 - 95,Male,0.005090,4,1

In [ ]:
smf.ols(formula='Yes % ~ Age', data=data_df).fit()